name: Deploy Flight Board

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  generate_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install requests
        
      # 1. index.html を生成する
      - name: Run data generator script
        run: python generate_flights.py
        env:
          AEROAPI_KEY: ${{ secrets.AEROAPI_KEY }}
          
      # ★★★ 新規追加ステップ：生成されたファイルをArtifactとして保存 ★★★
      - name: Upload generated index.html
        uses: actions/upload-artifact@v4
        with:
          name: deployment-files
          path: index.html # リポジトリのルートにある index.html を保存
          
      # 2. デプロイ専用のジョブを開始 (ファイルをダウンロードするため、別のジョブに分ける)
      - name: Download deployment files
        uses: actions/download-artifact@v4
        with:
          name: deployment-files
          path: . # カレントディレクトリ（ルート）にファイルをダウンロード
          
      # 3. GitHub Pagesにデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # ダウンロードしたファイルがあるルートディレクトリを指定
