name: Update Flight Board

on:
  # 5分ごとに実行
  schedule:
    - cron: '*/5 * * * *' 
  # 手動実行を可能にする
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run flight data generation script
        env:
          AVIATION_STACK_KEY: ${{ secrets.AVIATION_STACK_KEY }}
        run: |
          python generate_flights.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          files: index.html
          commit_message: "Auto-update: Flight board data refresh"
          branch: main # または master ブランチ名に合わせてください
